### PR TITLE
Missing BigQuery Options

### PR DESCRIPTION
**Pull request by blowmage**
The BigQuery load and extract methods are missing some options that are supported on the API.

Missing load options:

* allowJaggedRows
* allowQuotedNewlines
* encoding
* fieldDelimiter
* ignoreUnknownValues
* maxBadRecords
* quote
* schema
* skipLeadingRows

Missing extract options:

* compression
* fieldDelimiter
* printHeader

See also #370.

### CODE REVIEW

**Comment by blowmage** [comment]
@quartzmo This PR has all of the options identified except for `schema` on `Table#load`. It looks like this is there to load a file and create a table in one operation. Gcloud doesn't have a way to create a table and load a file in one operation, so I wonder if `schema` is needed. Thoughts?

**Comment by quartzmo** [comment]
@blowmage The optional parameter [configuration.load.schema](https://cloud.google.com/bigquery/docs/reference/v2/jobs#configuration.load.schema) is definitely not needed in this context, as the destination table is the resource represented here and already exists. At least that's how I read it:

> [Optional] The schema for the destination table. The schema can be omitted if the destination table already exists, or if you're loading data from Google Cloud Datastore.

**Comment by quartzmo** [comment]
Although, best would be to see if sending a schema allows a table that previously had no schema to be updated.

**Comment by blowmage** [comment]
Yeah, I can also see an argument for something like `Dataset#load` or `Project#load` that can be used to create and load in one API call.

**Comment by blowmage** [comment]
That said, I'm pretty comfortable with not supporting the option for the time being. Since we require two API calls the schema can be specified on table creation before the load.

**Comment by quartzmo** [comment]
Is this PR ready to merge then?

**Comment by blowmage** [comment]
Yeah.

**Comment by quartzmo** [comment]
Actually I just noticed something that should have been done in an earlier PR, but would be natural to fix here. Do you mind doc'ing the default value for `delimiter`?

**Comment by blowmage** [comment]
Yeah, no problem.

**Pull request merged**
