### PR TITLE
Fix internal method links, clean up library structure

### LINKED ISSUE #554: Method fragments not linked in jsondoc generation
In our docs, methods in the current context (e.g., "You can use {#update} to do..."), do not receive working links during JSON generation (they work fine in YARD's html output).

@callmehiphop wrote in [gcloud-common PR #65](https://github.com/GoogleCloudPlatform/gcloud-common/pull/65#issuecomment-183381793):

> It also looks like maybe there's a bug with the custom-type linking.. if you look at #update links at http://quartzmo.github.io/gcloud-ruby/#/docs/v0.6.1/dns/zone?method=import

YARD is failing to resolve these instance methods, even when provided the correct code object context containing them. The solution will be in our JSON generation on the `gcloud-jsondoc` branch.

### PR DESCRIPTION
**Pull request by quartzmo**
Also now leaves example captions wrapped in `p` elements.
Also includes a long-overdue major refactoring of project files.

[closes #554]

### CODE REVIEW

**Comment by quartzmo** [comment]
Please hold off on merging this while I investigate why [markdown code examples have no line breaks](http://quartzmo.github.io/gcloud-ruby/#/docs/v0.6.1/bigquery).

**Comment by quartzmo** [comment]
I restored the line breaks to the output.

@blowmage This PR is ready to merge.

**Comment by quartzmo** [comment]
Re-added `don't merge`, additional changes on the way!

**Comment by quartzmo** [comment]
Although there will be more changes ahead (after GoogleCloudPlatform/gcloud-common#102 is merged), I think this PR is already dangerously past the point where its changes can be easily understood. Please merge after inspection. I am removing `don't merge` now.

**Comment by blowmage** [comment]
I like the improvements to how the code is organized.

**Pull request merged**
