### PR TITLE
Pub/Sub Documentation Clarification

### PR DESCRIPTION
**Pull request by blowmage**

### CODE REVIEW

**Comment by quartzmo** [comment]
I've signed the CLA, I'm good to go.

**Comment by blowmage** [comment]
@jgeewax Have you seen googlebot do this before? Can we both push commits to a PR?

**Comment by jgeewax** [comment]
I can confirm that @blowmage and @quartzmo both signed the CLA. Good to merge if only those two authors are on the PR.

Double check that you've signed with the right e-mail addresses and all that too (commit author e-mail needs to match)

**Comment by tmatsuo** [comment]
LGTM

**Pull request merged**
