### PR TITLE
Add gcloud-common site

### PR DESCRIPTION
**Pull request by quartzmo**
Manually build and add site files from gcloud/common.

### CODE REVIEW

**Comment by blowmage** [comment]
Great job!

**Comment by quartzmo** [comment]
@callmehiphop PTAL! http://googlecloudplatform.github.io/gcloud-ruby/

**Comment by callmehiphop** [comment]
@quartzmo :+1: LGTM

**Comment by quartzmo** [comment]
@callmehiphop Thanks for reviewing it!

**Pull request merged**
