### PR TITLE
handling namespaces #404

### PR DESCRIPTION
**Pull request by jondot**
Based on @blowmage's suggestion

### CODE REVIEW

**Comment by quartzmo** [comment]
Rubocop caught what looks like a legitimate mistake for once! 

```ruby
if ns = opts[:namespace]
```

The entire output:
```sh
Running RuboCop...
Inspecting 79 files
....................................WC.........................................
Offenses:
lib/gcloud/datastore/connection.rb:70:32: C: Surrounding space missing in default value assignment.
      def run_query query, opts={}
                               ^
lib/gcloud/datastore/connection.rb:73:17: W: Assignment in condition - you probably meant to use ==.
          if ns = opts[:namespace]
                ^
lib/gcloud/datastore/dataset.rb:253:26: C: Surrounding space missing in default value assignment.
      def run query, opts={}
                         ^
```

**Comment by quartzmo** [comment]
No, I'm wrong, of course Rubocop didn't.

**Comment by quartzmo** [comment]
@jondot Is `bundle exec rubocop` in your local fork working for you? There are just a couple of small formatting fixes need (above). Let me know if this is giving you any trouble.

**Comment by blowmage** [comment]
@jondot Before we can accept this we need you to sign the Contributor agreement and fix the rubocop warnings.

**Comment by jondot** [comment]
Done and done :+1:

**Comment by quartzmo** [comment]
Sorry @jondot, can you please add documentation for the options hash and the option? Should be to easy copy/paste the boilerplate from another method.

**Comment by blowmage** [comment]
@quartzmo I think we can accept this and add the documentation later. We should document this in the Datastore overview guide as well, so we can update the parameter docs for this method when we do that.

@jondot Thanks for the contribution!

**Comment by jondot** [comment]
Thanks guys. I've enjoyed this discussion, as well as appreciate your swift response!
Offtopic - for the Google Platform guys - is there a chance the GAE Memcache facility makes its way to gcloud? (any other way accessing external to a GAE project?, on a different stack/cloud perhaps)

**Comment by quartzmo** [comment]
@jondot Thanks a lot! Please feel free to contribute again soon in the near future!

This [June 7 answer from a Google Cloud Platform team member](http://stackoverflow.com/a/30688739/901096) is all I could find for Memcache in Google Cloud Platform Compute Engine, but @jgeewax may know more.

**Pull request merged**
