### PR TITLE
Update README

### LINKED ISSUE #68: Update README.md to fit consistent style
See https://github.com/GoogleCloudPlatform/gcloud-meta/issues/3 for the format.

### PR DESCRIPTION
**Pull request by blowmage**
Changes to bring the README into alignment with the proposed format.

Closes #68

### CODE REVIEW

**Comment by blowmage** [comment]
@jgeewax So far this PR adds links to the homepage and API docs. The only sections in the proposal that are missing are "example applications" and "versioning". We don't have any example applications that I'm aware of, and we haven't discussed versioning. (I assume semver.) What would you like me to put for these? Are there other sections that are missing?

**Comment by jgeewax** [comment]
Are we OK with doing http://semver.org/ ?

if so, we can use the wording from gcloud-python:

> Versioning
> 
> This library follows Semantic Versioning.
> 
> It is currently in major version zero (0.y.z), which means that anything may change at any time and the public API should not be considered stable.

**Comment by blowmage** [comment]
I'm :+1: on using semver. I've updated the README to include a section on versioning. Anything else needed for the README?

**Comment by jgeewax** [comment]
If we're in line with https://github.com/GoogleCloudPlatform/gcloud-meta/issues/3 then we're all good.

**Pull request merged**
