### PR TITLE
Add Search::Fields

### PR DESCRIPTION
**Pull request by quartzmo**
This PR is currently a work in progress, exploring solutions for the [FieldValueList](https://cloud.google.com/search/reference/rest/google/cloudsearch/v1/FieldValueList) representation suggested by @blowmage in #413.

### CODE REVIEW

**Comment by quartzmo** [comment]
@blowmage When you look at this, don't worry too much about the implementation. I'm coding it test-first and so the implementation is only what it needs to be until we nail down the API. Look at and please provide feedback on the tests.

**Comment by blowmage** [comment]
I really like the direction this is going. I've had similar thoughts re implementation. As long as we have a great API defined in tests we should be free to change the internals as needed.

**Comment by quartzmo** [comment]
@blowmage This is an incomplete solution, but I feel it would be good to merge what I have done so far, so that we can more easily add to this foundation in parallel.

**Comment by blowmage** [comment]
Agreed. This direction is the way to to IMO.

**Pull request merged**
