### PR TITLE
Convert Logging to gRPC

### PR DESCRIPTION
**Pull request by blowmage**
Move the Logging service from using the REST API to the gRPC API.

This is a work in progress.

### CODE REVIEW

**Comment by blowmage** [comment]
This is nearly complete. The only things left are to revisit how we deal with serialized protobuf objects in a log entry's payload and checking the TODOs left in the code.

I also continue to see segfaults in some instances, but this should be fixed in the upcoming grpc 0.13.1 release. We may want to wait for that fix before cutting a release.

The tests are also an order of magnitude faster. 0.044959s vs. 0.448058s :grinning:

**Comment by quartzmo** [comment]
This is a big change. Reading it over again now.

**Comment by quartzmo** [comment]
FYI, here's what I got when I checked out this branch, ran `bundle install`, and ran the main test suite. (To shorten it, I removed some bundler and zonefile output where noted in brackets.)

```sh
Christophers-MacBook-Air:gcloud-ruby quartzmo$ git checkout --track blowmage/logging-grpc
Branch logging-grpc set up to track remote branch logging-grpc from blowmage.
Switched to a new branch 'logging-grpc'
Christophers-MacBook-Air:gcloud-ruby quartzmo$ bundle install
Fetching gem metadata from http://rubygems.org/.........
Fetching version metadata from http://rubygems.org/..
Resolving dependencies...
Using rake 10.5.0

[Using ... removed]

Installing google-protobuf 3.0.0.alpha.5.0.3
Installing grpc 0.13.0

[Using ... removed]

Bundle complete! 16 Gemfile dependencies, 66 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
Christophers-MacBook-Air:gcloud-ruby quartzmo$ b rake test
/Users/quartzmo/.rbenv/versions/2.2.3/gemsets/gcloud-ruby-yard/gems/grpc-0.13.0-universal-darwin/src/ruby/lib/grpc/errors.rb:30: warning: loading in progress, circular require considered harmful - /Users/quartzmo/.rbenv/versions/2.2.3/gemsets/gcloud-ruby-yard/gems/grpc-0.13.0-universal-darwin/src/ruby/lib/grpc.rb
	from /Users/quartzmo/.rbenv/versions/2.2.3/gemsets/gcloud-ruby-yard/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:4:in  `<main>'
	from /Users/quartzmo/.rbenv/versions/2.2.3/gemsets/gcloud-ruby-yard/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:4:in  `select'
	from /Users/quartzmo/.rbenv/versions/2.2.3/gemsets/gcloud-ruby-yard/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:9:in  `block in <main>'
	from /Users/quartzmo/.rbenv/versions/2.2.3/gemsets/gcloud-ruby-yard/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:9:in  `each'
	from /Users/quartzmo/.rbenv/versions/2.2.3/gemsets/gcloud-ruby-yard/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:10:in  `block (2 levels) in <main>'
	from /Users/quartzmo/.rbenv/versions/2.2.3/gemsets/gcloud-ruby-yard/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:10:in  `require'
	from /Users/quartzmo/code/google/codez/gcloud-ruby/test/gcloud/bigquery/copy_job_test.rb:15:in  `<top (required)>'
	from /Users/quartzmo/code/google/codez/gcloud-ruby/test/gcloud/bigquery/copy_job_test.rb:15:in  `require'
	from /Users/quartzmo/code/google/codez/gcloud-ruby/test/helper.rb:15:in  `<top (required)>'
	from /Users/quartzmo/code/google/codez/gcloud-ruby/test/helper.rb:15:in  `require'
	from /Users/quartzmo/.rbenv/versions/2.2.3/gemsets/gcloud-ruby-yard/gems/grpc-0.13.0-universal-darwin/src/ruby/lib/grpc.rb:35:in  `<top (required)>'
	from /Users/quartzmo/.rbenv/versions/2.2.3/gemsets/gcloud-ruby-yard/gems/grpc-0.13.0-universal-darwin/src/ruby/lib/grpc.rb:35:in  `require'
	from /Users/quartzmo/.rbenv/versions/2.2.3/gemsets/gcloud-ruby-yard/gems/grpc-0.13.0-universal-darwin/src/ruby/lib/grpc/errors.rb:30:in  `<top (required)>'
	from /Users/quartzmo/.rbenv/versions/2.2.3/gemsets/gcloud-ruby-yard/gems/grpc-0.13.0-universal-darwin/src/ruby/lib/grpc/errors.rb:30:in  `require'
/Users/quartzmo/.rbenv/versions/2.2.3/gemsets/gcloud-ruby-yard/gems/grpc-0.13.0-universal-darwin/src/ruby/lib/grpc/core/time_consts.rb:30: warning: loading in progress, circular require considered harmful - /Users/quartzmo/.rbenv/versions/2.2.3/gemsets/gcloud-ruby-yard/gems/grpc-0.13.0-universal-darwin/src/ruby/lib/grpc.rb
	from /Users/quartzmo/.rbenv/versions/2.2.3/gemsets/gcloud-ruby-yard/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:4:in  `<main>'
	from /Users/quartzmo/.rbenv/versions/2.2.3/gemsets/gcloud-ruby-yard/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:4:in  `select'
	from /Users/quartzmo/.rbenv/versions/2.2.3/gemsets/gcloud-ruby-yard/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:9:in  `block in <main>'
	from /Users/quartzmo/.rbenv/versions/2.2.3/gemsets/gcloud-ruby-yard/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:9:in  `each'
	from /Users/quartzmo/.rbenv/versions/2.2.3/gemsets/gcloud-ruby-yard/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:10:in  `block (2 levels) in <main>'
	from /Users/quartzmo/.rbenv/versions/2.2.3/gemsets/gcloud-ruby-yard/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:10:in  `require'
	from /Users/quartzmo/code/google/codez/gcloud-ruby/test/gcloud/bigquery/copy_job_test.rb:15:in  `<top (required)>'
	from /Users/quartzmo/code/google/codez/gcloud-ruby/test/gcloud/bigquery/copy_job_test.rb:15:in  `require'
	from /Users/quartzmo/code/google/codez/gcloud-ruby/test/helper.rb:15:in  `<top (required)>'
	from /Users/quartzmo/code/google/codez/gcloud-ruby/test/helper.rb:15:in  `require'
	from /Users/quartzmo/.rbenv/versions/2.2.3/gemsets/gcloud-ruby-yard/gems/grpc-0.13.0-universal-darwin/src/ruby/lib/grpc.rb:40:in  `<top (required)>'
	from /Users/quartzmo/.rbenv/versions/2.2.3/gemsets/gcloud-ruby-yard/gems/grpc-0.13.0-universal-darwin/src/ruby/lib/grpc.rb:40:in  `require'
	from /Users/quartzmo/.rbenv/versions/2.2.3/gemsets/gcloud-ruby-yard/gems/grpc-0.13.0-universal-darwin/src/ruby/lib/grpc/core/time_consts.rb:30:in  `<top (required)>'
	from /Users/quartzmo/.rbenv/versions/2.2.3/gemsets/gcloud-ruby-yard/gems/grpc-0.13.0-universal-darwin/src/ruby/lib/grpc/core/time_consts.rb:30:in  `require'
/Users/quartzmo/.rbenv/versions/2.2.3/gemsets/gcloud-ruby-yard/gems/os-0.9.6/lib/os.rb:154: warning: mismatched indentations at 'end' with 'for' at 151
/Users/quartzmo/.rbenv/versions/2.2.3/gemsets/gcloud-ruby-yard/gems/os-0.9.6/lib/os.rb:158: warning: assigned but unused variable - kb
/Users/quartzmo/.rbenv/versions/2.2.3/gemsets/gcloud-ruby-yard/gems/os-0.9.6/lib/os.rb:198: warning: mismatched indentations at 'end' with 'def' at 190
/Users/quartzmo/.rbenv/versions/2.2.3/gemsets/gcloud-ruby-yard/gems/os-0.9.6/lib/os.rb:240: warning: mismatched indentations at 'end' with 'case' at 218

[zonefile warnings removed]

/Users/quartzmo/.rbenv/versions/2.2.3/gemsets/gcloud-ruby-yard/gems/google-protobuf-3.0.0.alpha.5.0.3-universal-darwin/lib/google/protobuf/repeated_field.rb:108: warning: method redefined; discarding old slice
/Users/quartzmo/.rbenv/versions/2.2.3/lib/ruby/2.2.0/forwardable.rb:181: warning: previous definition of slice was here
/Users/quartzmo/code/google/codez/gcloud-ruby/lib/gcloud/datastore/proto.rb:116: warning: possibly useless use of a variable in void context
Run options: --seed 28385

# Running:

.....................................

[zonefile warnings removed]
.......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

Finished in 8.825467s, 123.9594 runs/s, 616.8512 assertions/s.

1094 runs, 5444 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by quartzmo** [comment]
@blowmage points out that the `circular require considered harmful` warning above is addressed in https://github.com/grpc/grpc/issues/4130.

**Pull request merged**
