### PR TITLE
Translate docs

### PR DESCRIPTION
**Pull request by quartzmo**
[refs #627]

### CODE REVIEW

**Comment by blowmage** [comment]
@quartzmo This looks good! Do you have the docs built on your github account?

**Comment by quartzmo** [comment]
@blowmage Demo docs are allmost there!

**Comment by quartzmo** [comment]
@blowmage https://quartzmo.github.io/gcloud-ruby/#/docs/master/gcloud/translate (still with the dark theme.)

I just noticed code object links in the guide are not working, looking into that now. Please hold off on merging.

**Comment by blowmage** [comment]
The [docs](https://quartzmo.github.io/gcloud-ruby/#/docs/master/gcloud/translate) look fantastic.

**Comment by blowmage** [comment]
Great job as always!

**Pull request merged**
