### PR TITLE
Add additional functionality to Vision

### PR DESCRIPTION
**Pull request by blowmage**
Additional functionality for Vision service implementation.

- [x] Allow multiple images to be processed with different annotate options. (#659)
- [x] Run full analysis with empty options (#660)
- [x] Set default value on Image analysis helper methods (#661)
- [x] Allow ImageContext to be set on analysis (#662)

### CODE REVIEW

**Comment by blowmage** [comment]
@quartzmo Can you take a lookout this functionality? I believe this brings the Vision implementation to feature completeness. Obviously missing lots of documentation though...

**Comment by quartzmo** [comment]
@blowmage Pulling your branch and looking at it now!

**Comment by blowmage** [comment]
The main tradeoff on setting ImageContext is that you have to create an Image object first, and update the context on the Image object, as opposed to adding additional values to the `annotate` call.

```ruby
image = vision.image filepath
image.context.location = { longitude: -122.0862462, latitude: 37.4220041 }
analysis = vision.annotate image, landmarks: 10
```

vs. 

```ruby
analysis = vision.annotate filepath, landmarks: 10,
  location: { longitude: -122.0862462, latitude: 37.4220041 }
```

And...

```ruby
image = vision.image filepath
image.context.languages = ["en", "es"]
analysis = vision.annotate image, text: true
```

vs. 

```ruby
analysis = vision.annotate image, text: true, language_hints: ["en", "es"]
```

Setting those values on the Image object is a little more work for users, but `annotate` already has so many optional arguments and I didn't feel comfortable adding even more. Also, keeping it on the Image object allows the ImageContext API to expand if it needs to add more options beyond location and image hints. Feels a bit more OO and comfortable to me. Thoughts?

**Comment by blowmage** [comment]
Another reason to only allow ImageContext to be configured on an Image object is that it avoids adding additional optional arguments not just on `Project#annotate`, but `Image#texts`, and `Image#text`, and `Image#landmarks`, and `Image#landmark`, etc...

**Comment by quartzmo** [comment]
@blowmage, I agree with you: I prefer the first examples in which the `Image` parameter collects the metadata  configuration (`latLongRect ` and `languageHints` currently, possibly more in the future, as you say.) I consider calling `annotate` with just a filepath is a convenience/shortcut, and it is OK that it doesn't support this more advanced configuration.

However, now that I've looked at this, I have a couple of observations:

1. Can we accept the context args in `Project#image`, to avoid forcing the need to call nested setters on the Image/Context after construction? (Saves a line...)

  ```ruby
  image = vision.image filepath, language_hints: ["en", "es"]
  analysis = vision.annotate image, text: true
  ```

2. Shouldn't the location parameter be a type that enforces the contract of [`latLongRect `](https://cloud.google.com/vision/reference/rest/v1/images/annotate#LatLongRect), meaning a pair of lat/long values, `minLatLng ` and `maxLatLng `?

**Comment by blowmage** [comment]
> 1. Can we accept the context args in `Project#image`

We _could_, but I'd like to not. The reason for this is kinda involved. When we've had lots of options on object constructors its because we are calling an API method to create the resource. [`Gcloud::Storage::Project#create_bucket`](https://googlecloudplatform.github.io/gcloud-ruby/#/docs/master/gcloud/storage/project?method=create_bucket-instance) is a great example of this. There are so many optional arguments in the constructor that are also methods on the Bucket object, because those values are needed during the resource creation. But for vision's Image we don't create a resource on the service, and so I'd rather we didn't. It keeps the API surface areas smaller.

> 2. Shouldn't the location parameter be a type that enforces the contract of `latLongRect`?

That is correct. 100% my bad. I'll update the code to not be busted.

**Comment by quartzmo** [comment]
@blowmage Sounds good. On 1., I prefer immutable objects and directly calling constructors, but that's just my personal preference, I don't think it's an important issue here.

**Comment by quartzmo** [comment]
How do you feel about renaming `Color#rgb` to `Color#hex`, since most people use "hex" to refer to this encoding of the rgb values. (See endless "rgb to hex" converters online, also [wikipedia](https://en.wikipedia.org/wiki/Web_colors#Hex_triplet).)

**Comment by blowmage** [comment]
Perhaps I'm showing my age, but that six character representation of a color is `rgb`, although I'm fine aliasing it as `hex`. The Color object already has `red`, `green`, and `blue` integer values, so the object is inherently the decimal format already. The only conversion we make is to the hex code, and I think its fine to name it `rgb`. But that's just me...

I also pronounce "gif" with a hard G.

**Comment by quartzmo** [comment]
Area looks good to me, merging!

**Pull request merged**
