### PR TITLE
Add Vision Service

### PR DESCRIPTION
**Pull request by blowmage**
Add the Vision API implementation.

This includes the changes on the annotation features maximum results discussed in the comments on #679.

Full documentation can be seen [here](https://quartzmo.github.io/gcloud-ruby/#/docs/master/gcloud/vision).

### CODE REVIEW

**Comment by blowmage** [comment]
@jgeewax Can you give feedback on this?

**Comment by jgeewax** [comment]
@blowmage : Don't manually edit the `cla: no` tag -- let googlebot do that. @quartzmo , can you comment on the issue just to confirm for googlebot that you signed the CLA and meant for these commits to end up here?

This happens anytime someone is merging commits that belonged to someone else -- you may have signed the CLA, but googlebot wants to be sure you intended for these particular commits to end up in this repo.

**Comment by quartzmo** [comment]
I signed the CLA and meant for these commits to end up here.

**Comment by quartzmo** [comment]
@jgeewax Did it get hung up somehow?

**Comment by jgeewax** [comment]
@googlebot PTAL?

**Comment by blowmage** [comment]
I have signed the Contributor License Agreement and these are my commits.

**Comment by quartzmo** [comment]
I have signed the Contributor License Agreement and these are my commits.

**Comment by blowmage** [comment]
I have also signed the Contributor License Agreement and these are still my commits.

**Comment by blowmage** [comment]
I don't remember googlebot switching a PR with multiple contributors back to "cla:yes"... Doing it manually.

**Comment by quartzmo** [comment]
I think we're ready to release Vision. Merging!

**Pull request merged**
