### PR TITLE
Add block-based Bucket#update and Bucket#cors

### LINKED ISSUE #279: Storage Bucket Update
Allow multiple attributes to be changed in a single API request.

```ruby
bucket.update do |b|
  b.website_main = "index.html"
  b.website_404 = "not_found.html"
end
```

### PR DESCRIPTION
**Pull request by quartzmo**
[closes #279, #375]

### CODE REVIEW

**Comment by quartzmo** [comment]
@blowmage This PR is ready for review, and if it looks good, merging.

**Comment by blowmage** [comment]
How are CORS rules removed or updated?

**Comment by quartzmo** [comment]
I thought about that, of course, but couldn't come up with anything. As far as I know, the rules are completely non-unique. If you want to change or remove one, it's a matter of "you'll know it when you see it". So you need to inspect all attributes of each record to be sure of what you're doing. I think the best approach is to work with the mutable "raw" (array of hashes) representation within a `Bucket#update` block. But feel free to suggest a concrete design if you have one, I'd be more than happy to add it.

**Comment by blowmage** [comment]
I understand that finding a CORS rule to replace or remove is difficult, because there is no unique identifiers. BigQuery's schema is also difficult to modify because, by definition, the schema can only be added to, but we still have the option in the schema DSL to replace the schema by a new schema defined in the DSL. But CORS doesn't even have that.

I think it would be good to have a mutable array of hashes in the DSL, that you can use to find and possibly remove a rule, as well as the `add_rule` helper method.

```ruby
bucket.cors do |cors|
  # Remove the first CORS hash in the array
  cors.shift
  # Remove all existing rules that include example.org
  cors.delete_if { |cors_hash| cors_hash["origin"].includes? "http://example.org" }
  # Add new rule
  cors.add_rule 300, [ "http://example.org", "https://example.org" ],
                [ "*" ],
                [ "Content-Type" ]
end
```

**Comment by quartzmo** [comment]
@blowmage The array is a great idea, I'll do it. Update coming soon. Thanks!

**Comment by blowmage** [comment]
Love it! The added functionality and tests is terrific!

**Pull request merged**
