### PR TITLE
Improve Vision acceptance test coverage

### PR DESCRIPTION
**Pull request by blowmage**

### CODE REVIEW

**Comment by blowmage** [comment]
Here is the code coverage changes:

```
lib/gcloud/vision.rb	94.74% -> 95.24%
lib/gcloud/vision/annotate.rb	97.92% -> 100.0%
lib/gcloud/vision/annotation.rb	75.0% -> 92.19%
lib/gcloud/vision/annotation/entity.rb	58.54% -> 87.8%
lib/gcloud/vision/annotation/face.rb	50.69% -> 74.38%
lib/gcloud/vision/annotation/properties.rb	81.13% -> 81.13%
lib/gcloud/vision/annotation/safe_search.rb	86.11% -> 86.11%
lib/gcloud/vision/annotation/text.rb	77.19% -> 77.19%
lib/gcloud/vision/annotation/vertex.rb	81.82% -> 81.82%
lib/gcloud/vision/credentials.rb	100.0% -> 100.0%
lib/gcloud/vision/image.rb	79.26% -> 79.26%
lib/gcloud/vision/location.rb	73.91% -> 78.26%
lib/gcloud/vision/project.rb	94.59% -> 94.29%
lib/gcloud/vision/service.rb	92.31% -> 92.59%
```

Most (all?) of the remaining uncovered code are methods like `#to_h` and `#inspect`.

**Comment by blowmage** [comment]
I decided to place actual annotation values in the test even though there is a chance that the vision service implementation might change and the results would vary over time. But I figured it might be interesting to know if it does change, and it shouldn't be too difficult to change the acceptance tests when/if that happened.

**Comment by quartzmo** [comment]
This looks great and will give us a lot more confidence with Vision. It will be interesting to see if some of these assertions break in the future as the service evolves. (I'm thinking of things like `label.description.must_equal "stone carving"`. It's machine learning, after all.)

**Comment by quartzmo** [comment]
@blowmage ^ I was just writing up the same thought. I completely agree.

**Comment by quartzmo** [comment]
These tests all pass for me locally. Merging.

**Pull request merged**
