### PR TITLE
Datastore changes

### PR DESCRIPTION
**Pull request by blowmage**
This PR contains the changes to the public API to reflect the differences in v1beta3. For the most part, these changes are additive and backwards compatible with previous releases.

The changes include:

- [x] Add `QueryResults#next?`, `QueryResults#next`, and `QueryResults#all`
- [x] Renaming `Key#dataset_id` to `Key#project`
- [x] Updating `Dataset#key` and `Dataset#entity` convenience methods to make creation of nested keys easier
- [x] Removal of `ApiError` (Breaking change)
- [x] Remove old Proto file
- [x] Blob support (#653)
- [x] Location support (Geo Point, Lat/Lon)
- [x] Support Date and DateTime when setting a Timestamp (#654)
- [x] Support ReadOptions (#618, #655)
- [x] Don't set project_id on PartitionId (#651)
- [x] Batch commits (#652)

### CODE REVIEW

**Comment by vyper** [comment]
Connection don't work using [emulator](https://cloud.google.com/datastore/docs/tools/datastore-emulator).

I received this error and console stay freezed after error:

```
> dataset.save entity
E0428 17:56:05.215965000 123145303928832 resolve_address_posix.c:126] getaddrinfo: nodename nor servname provided, or not known
```

**Comment by blowmage** [comment]
The current emulator doesn't support GRPC. You can download the updated emulator [here](https://storage.googleapis.com/gcd/tools/gcd-grpc-1.0.0.zip). This is still a WIP.

**Comment by vyper** [comment]
Oh! Thanks @blowmage. I'm using your branch in tests. :grin:

**Comment by blowmage** [comment]
You should probably build the google-protobuf gem from their master branch then. There is an unreleased fix coming from them that we are waiting on. It's been a thing...

**Comment by blowmage** [comment]
I believe this PR is ready for consideration.

**Comment by quartzmo** [comment]
@blowmage Is "Renaming Key#dataset_id to Key#project" a breaking change? If so, can you indicate in PR description for later inclusion in release notes?

**Comment by blowmage** [comment]
It is not a breaking change. There is an alias named `dataset_id` so old code will continue to work.

**Comment by quartzmo** [comment]
Time to get this into `datastore` branch! Merging! Thanks for this big bundle of additions @blowmage!

**Pull request merged**
