### PR TITLE
Add gcloud-java link to landing page dropdown menu

### PR DESCRIPTION
**Pull request by ajkannan**
Here's what the site would look like with the change: http://ajkannan.github.io/gcloud-ruby/

(Click on the dropdown menu on the top left)

refs #253

### CODE REVIEW

**Comment by blowmage** [comment]
@jgeewax Is this the image and the order of the projects you want to use?

**Comment by jgeewax** [comment]
- Order should be alphabetical so that looks fine.
- Image should be the white one we used elsewhere.

**Comment by blowmage** [comment]
What is the image used elsewhere? All I have found so far is the image of Duke that is in this pull request, it is used on the python and java sites.

I think the java image would look more in line with the other projects if it were a single toned flat graphic, and not the 3D rendered Duke that is in this PR. Bonus for being SVG.

**Comment by jgeewax** [comment]
See https://github.com/GoogleCloudPlatform/gcloud-node/pull/828#issuecomment-135466803

**Comment by blowmage** [comment]
The URL to the image is http://callmehiphop.github.io/gcloud-node/site/img/icon-lang-java.svg

Here are the contents:

```xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 19.1.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
   width="24px" height="24px" viewBox="0 0 24 24" enable-background="new 0 0 24 24;" xml:space="preserve">
<style type="text/css">
  .st0{fill:#FFFFFF;}
  .st1{fill:none;}
</style>
<g>
  <g>
    <path class="st0" d="M15,0c0.2,0,0.4,0,0.5,0C15.8,0.1,16,0.3,16,0.5c0.1,0.4,0.2,0.8,0.3,1.2c0.1,0.3,0.1,0.6,0.4,0.9
      c0.1-0.4,0.2-0.8,0.4-1.2c0.2-0.4,0.4-0.7,0.9-0.8c0.4-0.1,0.7,0.1,0.7,0.6c0,0.2-0.1,0.5-0.2,0.7c-0.3,0.6-0.4,1.3-0.2,2
      c0.1,0.5,0.2,1,0.2,1.6c-0.1,0.4-0.3,0.7-0.6,1c-0.1,0.1-0.3,0.2-0.4,0.4c-0.2,0.3-0.3,0.6-0.3,0.9c0,0.6,0,1.1,0,1.7
      c0,0.3-0.1,0.6-0.3,0.9c-0.3,0.4-0.4,0.9-0.5,1.4c0,0.5,0.1,1.1,0.3,1.6c0.3,0.6,0.5,1.3,0.7,1.9c0.4,1.1,0.6,2.3,0.7,3.5
      c0.1,0.6,0.1,1.2,0.1,1.8c0,0.4,0,0.8-0.1,1.2c0,0.5-0.1,1-0.3,1.4c-0.1,0.3-0.2,0.5-0.5,0.7c-0.2,0.1-0.4,0.2-0.7,0.3
      c-0.3,0-0.6,0-0.9-0.3c-0.2-0.3-0.4-0.5-0.6-0.8c-0.4-0.5-0.7-1.1-1.2-1.5c-0.5-0.5-1.1-0.7-1.8-0.6c-0.5,0.1-1,0.3-1.4,0.6
      c-0.7,0.5-1.3,1-1.9,1.5c-0.4,0.3-0.8,0.6-1.2,0.7c-0.4,0.1-0.8,0-0.9-0.5c-0.1-0.4-0.1-0.7-0.1-1.1c0-0.3,0-0.7,0-1
      c-0.1,0-0.2,0.1-0.3,0.1c-0.4,0-0.7-0.1-0.9-0.5c0-0.1,0-0.3,0-0.4c0-0.1,0.1-0.1,0.1-0.2c0.2-0.3,0.4-0.6,0.6-0.9
      c0.4-0.5,0.5-1.1,0.4-1.7c-0.1-0.3-0.2-0.7-0.3-1c-0.1-0.4-0.1-0.8,0-1.2s0.3-0.7,0.6-1c0.5-0.6,0.8-1.2,1.1-1.9
      c0.3-0.8,0.3-1.6,0.4-2.5c0-0.4,0.1-0.9,0.1-1.3c0-0.5,0.1-1.1,0.1-1.6c0-1.1,0-2.2,0-3.3c0-0.2,0-0.3-0.1-0.5
      c0-0.2-0.1-0.4-0.1-0.6c0.1,0,0.1,0,0.1,0.1C8.9,3.1,9.5,3.5,10,3.9c0.5,0.4,0.9,0.9,1.4,1.4c0.4,0.4,0.7,0.8,1.1,1.2
      c0.4,0.5,0.8,0.9,1.1,1.4c0.5,0.6,0.9,1.3,1.3,2c0.2,0.3,0.4,0.4,0.7,0.3c0.4-0.1,0.8-0.3,0.9-0.8c0.2-0.7,0.1-1.3-0.1-2
      c-0.1-0.2-0.2-0.3-0.4-0.3c-0.4,0-0.7-0.2-1-0.4c-0.3-0.2-0.6-0.3-1-0.2c-0.1,0-0.3,0.1-0.5,0.1c-0.1,0-0.3,0-0.4,0
      c-0.3-0.2-0.4-0.7-0.1-1c0.2-0.2,0.4-0.3,0.6-0.4c0.2-0.1,0.4-0.1,0.6-0.2c-0.2-0.2-0.3-0.4-0.5-0.6c-0.5-0.6-0.8-1.3-1-2.1
      c-0.1-0.5-0.1-0.9,0.3-1.1C13.5,1,13.8,1,14,1.4c0.2,0.3,0.3,0.7,0.5,1.1c0.1,0.2,0.3,0.4,0.4,0.5c0,0,0,0,0.1,0
      c0-0.2-0.1-0.4-0.1-0.5c-0.1-0.5-0.2-0.9-0.2-1.4c0-0.1,0-0.3,0-0.4C14.7,0.3,14.8,0.1,15,0z M13.6,9.6c0,0.2,0.1,0.5,0.1,0.7
      c0,0.4-0.1,0.9-0.3,1.3c-0.4,0.7-1,1.1-1.7,1.3c-0.4,0.1-0.7,0.1-1.1,0.1c-0.6-0.1-1-0.3-1.4-0.8C9.1,12.1,9,12,8.9,12
      c-0.1,0.1-0.1,0.1-0.2,0.2c-0.2,0.7-0.3,1.4-0.5,2.2c-0.1,0.7-0.3,1.4-0.4,2.2c-0.1,0.5-0.2,1.1-0.3,1.6c-0.1,0.5-0.2,0.9-0.2,1.4
      c-0.1,0.4-0.1,0.8-0.1,1.3c-0.1,0.5-0.1,1.1,0,1.6c0.1,0.4,0.2,0.5,0.6,0.3c0.3-0.2,0.6-0.4,0.9-0.6c0.4-0.3,0.8-0.7,1.1-1
      c0.7-0.5,1.4-1,2.3-1.1c0.4,0,0.8,0,1.2,0.1c0.7,0.3,1.3,0.8,1.7,1.4c0.4,0.5,0.7,1,1,1.5c0.1,0.1,0.2,0.2,0.3,0.2
      c0.4,0.1,0.6,0,0.8-0.4c0.1-0.2,0.1-0.3,0.1-0.5c0.1-0.7,0.1-1.4,0.2-2c0-0.7,0-1.3-0.1-2c-0.1-0.5-0.2-1.1-0.3-1.6
      c-0.2-0.7-0.4-1.3-0.6-2c-0.3-0.9-0.7-1.8-1.1-2.7c-0.4-0.8-0.9-1.6-1.3-2.4c-0.1-0.2-0.2-0.2-0.4-0.1C13.7,9.5,13.6,9.6,13.6,9.6
      z M11.4,8.8c-0.1,0-0.2,0-0.4,0c-0.5,0.1-0.9,0.3-1.3,0.6C9.3,9.8,9,10.3,9.1,10.9c0.1,0.5,0.3,0.9,0.7,1.1c0.5,0.3,1,0.4,1.5,0.3
      c0.4-0.1,0.8-0.2,1.2-0.5c0.5-0.5,0.7-1,0.6-1.7c0-0.4-0.2-0.7-0.4-0.9C12.3,8.9,11.9,8.7,11.4,8.8z M7,17.1c0-0.1,0-0.2,0-0.2
      c0.1-0.6,0.2-1.2,0.3-1.8c0-0.1,0.1-0.3,0-0.4C6.8,15.2,6.4,16,7,17.1z"/>
    <path class="st1" d="M13.6,9.6c0.1,0,0.1,0,0.2,0c0.1,0,0.3,0,0.4,0.1c0.4,0.8,0.9,1.6,1.3,2.4c0.4,0.9,0.8,1.8,1.1,2.7
      c0.2,0.6,0.4,1.3,0.6,2c0.1,0.5,0.2,1.1,0.3,1.6c0.1,0.7,0.1,1.3,0.1,2c0,0.7-0.1,1.4-0.2,2c0,0.2-0.1,0.4-0.1,0.5
      c-0.1,0.3-0.4,0.5-0.8,0.4c-0.1,0-0.2-0.1-0.3-0.2c-0.4-0.5-0.7-1-1-1.5c-0.5-0.6-1-1.1-1.7-1.4c-0.4-0.1-0.8-0.2-1.2-0.1
      c-0.9,0.1-1.6,0.5-2.3,1.1c-0.4,0.3-0.8,0.7-1.1,1c-0.3,0.2-0.6,0.4-0.9,0.6c-0.4,0.2-0.5,0.1-0.6-0.3c-0.1-0.5,0-1.1,0-1.6
      c0.1-0.4,0.1-0.8,0.1-1.3c0.1-0.5,0.1-0.9,0.2-1.4c0.1-0.5,0.2-1.1,0.3-1.6c0.1-0.7,0.3-1.4,0.4-2.2s0.3-1.4,0.5-2.2
      c0-0.1,0.1-0.1,0.2-0.2c0.1,0,0.1,0.1,0.2,0.1c0.4,0.4,0.9,0.7,1.4,0.8c0.4,0.1,0.8,0,1.1-0.1c0.7-0.2,1.3-0.6,1.7-1.3
      c0.2-0.4,0.3-0.8,0.3-1.3C13.7,10,13.6,9.8,13.6,9.6z"/>
    <path class="st1" d="M9.9,10c0.2,0,0.5-0.2,0.6-0.4c0-0.1,0-0.2-0.1-0.2c-0.2,0-0.5,0.2-0.5,0.4C9.7,9.9,9.7,10,9.9,10z"/>
    <path class="st1" d="M7,17.1c-0.6-1.2-0.3-1.9,0.3-2.5c0.1,0.1,0.1,0.3,0,0.4c-0.1,0.6-0.2,1.2-0.3,1.8C7.1,17,7.1,17,7,17.1z"/>
    <path class="st0" d="M9.9,10c-0.2,0-0.2-0.1-0.1-0.2c0.1-0.2,0.4-0.4,0.5-0.4c0.1,0,0.2,0.1,0.1,0.2C10.4,9.8,10,10,9.9,10z"/>
  </g>
</g>
</svg>
```

**Comment by blowmage** [comment]
@ajkannan Do you want to update this PR or do you want me to close this with a competing PR?

**Comment by ajkannan** [comment]
I can update this PR.

**Comment by blowmage** [comment]
@ajkannan Thanks! Do you have a URL that links to the latest version of the documentation? On node [/gcloud-node/#/docs](https://googlecloudplatform.github.io/gcloud-node/#/docs) always does this, and on Python it is [/gcloud-python/latest/](http://googlecloudplatform.github.io/gcloud-python/latest/), and on Ruby it is [/gcloud-ruby/docs/latest](http://googlecloudplatform.github.io/gcloud-ruby/docs/latest).

**Comment by ajkannan** [comment]
gcloud-java uses the javadocs template for it's docs, which doesn't link back to the other languages.  JJ weighed in yesterday (https://github.com/GoogleCloudPlatform/gcloud-python/pull/1095#issuecomment-135181691), and he thought it best to link back to the landing page instead of the javadocs page.

**Comment by blowmage** [comment]
:+1:

**Pull request merged**
