### PR TITLE
Add chunk_size support to Gcloud::Bigquery::Table#load method

### PR DESCRIPTION
**Pull request by gramos74**
In the tests I'm checking that the file is resumable because otherwise we get a false positive.

### CODE REVIEW

**Comment by quartzmo** [comment]
@gramos74 Thanks a lot! Our hope is to get this into a release that we plan for today.

Can you refactor this method to pass the rubocop checks?

```sh
lib/gcloud/bigquery/table.rb:754:7: C: Method has too many lines. [17/15]
      def load file, format: nil, create: nil, write: nil,
```

**Comment by gramos74** [comment]
:)

**Comment by quartzmo** [comment]
This PR:

[fixes #701]

**Comment by gramos74** [comment]
Should I rebase both commits ?

**Comment by blowmage** [comment]
@gramos74 Yeah, can you squash these two commits into one?

**Comment by gramos74** [comment]
Done

**Comment by blowmage** [comment]
Awesome! Thank you so much for your contribution!

**Comment by gramos74** [comment]
my pleasure

**Comment by quartzmo** [comment]
Thanks again @gramos74!

**Pull request merged**
