### PR TITLE
Add timeout optional argument

### PR DESCRIPTION
**Pull request by blowmage**
This is an extension of the existing API. We don't currently allow users to specify a timeout. Part of the challenge is how we would support the feature as we move from Google API Client 0.8 to 0.9 and eventually to GRPC and GAX. I believe we should be able to support this API across all those implementations.

### CODE REVIEW

**Comment by blowmage** [comment]
I did not specify what the default timeout is when none is set, but I could not figure out what the timeout is in Hurley or HTTPClient. The gRPC timeout is _infinity_. So I felt it best to not say in the documentation exactly what the default timeout was.

**Comment by blowmage** [comment]
This does work across GAPI and GRPC services:

```ruby
gcloud.storage(timeout: 0.1).buckets.count
#=> Gcloud::Error: execution expired
gcloud.pubsub(timeout: 0.1).topics.count
#=> Gcloud::DeadlineExceededError: 4:Deadline Exceeded
```

**Comment by quartzmo** [comment]
I think moving the timeout configuration from a single global variable to the project instances is a great change.

**Comment by gramos74** [comment]
Sorry... I was not at home.

I saw the code and looks really good. I agree with Chris that moving out the timeout variable from the global configuration is great.

But I have a question... maybe it's a bit stupid... I'm not able to see how Hurley use that timeout_sec. Could you let me know  ? ( It's simple interest in order to know a bit more the flow ).

**Pull request merged**
