### PR TITLE
Introduce gRPC and Gapic client for Cloud Language API.

### PR DESCRIPTION
**Pull request by jmuk**
Gapic client (language_service_api.rb) and its config (_config.json)
are the wrapper automatically generated from the proto definition
and API configs.

### CODE REVIEW

**Comment by jmuk** [comment]
Hi, any feedback?

I don't want to rush you, but I just want to confirm that this is not forgotten.

**Comment by blowmage** [comment]
Hey Jun, haven't forgotten. :) We are waiting to get #813 accepted and then we will create a new gem for language. The file locations will just be different is all.

**Comment by blowmage** [comment]
@jmuk Can you revise this PR and move the files to `google-cloud-language/lib`?

**Comment by jmuk** [comment]
Rebased, now they are located under `google-cloud-language/lib`.

**Comment by quartzmo** [comment]
@jmuk Thank you!

**Comment by jmuk** [comment]
Ugh, rubocop failures... 😞 

I'll fix some of them, but probably I'll make exceptions for line lengths and exclude gRPC generated files.

**Comment by blowmage** [comment]
I'd exclude all the files you are adding in `google-cloud-language/.rubocop`.

**Comment by blowmage** [comment]
@jmuk Hah! You don't need to disable the rubocop rule if you correct the syntax. :)

Go ahead and remove that line disabling the rule and squash all the commits into one and we'll get this accepted.

**Comment by blowmage** [comment]
You can also run the rubocop report with the following:

```
cd google-cloud-language
rake rubocop
```

**Comment by blowmage** [comment]
Although you might need to run `bundle install` as well. :)

**Comment by blowmage** [comment]
Awesome! Thanks @jmuk!

**Pull request merged**
